version: "3"
services:
  vue:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    command: yarn dev
    volumes:
      - .:/code
      - /code/node_modules
    networks:
      - webnet
    ports:
      - "4000:4000"
    env_file: ./config/.env
    environment:
      DEV_HOST: "0.0.0.0"

networks:
  webnet:
