# Default compose file for development and production.
# Should be used directly only in development.

version: "3"
services:
  vue:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
      args:
        APP_ENV: "development"
    command: yarn dev
    volumes:
      - .:/code
      - /code/node_modules
    networks:
      - webnet
    env_file: ./config/.env
    environment:
      DEV_HOST: "0.0.0.0"

networks:
  webnet:
