language: node_js

sudo: true

node_js: 9.4

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules

services:
  - docker

env:
  - PROJECT_NAME: wemake-vue-demo

before_install:
  - sudo apt-get update && sudo apt-get install expect
  - sudo pip install -U docker-compose
  - docker --version && docker-compose --version

install:
  - yarn install

script:
  - sh tests/test.sh

deploy:
  provider: script
  script: sh tests/deploy.sh
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: change
