language: node_js

sudo: true

cache:
  directories:
    - node_modules

node_js: 8

services:
  - docker

install:
  - sudo apt-get update && sudo apt-get install expect
  - yarn install

script:
  - sh test.sh

notifications:
  email:
    on_success: never
    on_failure: change
