language: node_js

sudo: true

node_js: 9.10.1

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules

services:
  - docker

env:
  - PROJECT_NAME: wemake_vue_demo

before_install:
  - sudo apt-get update && sudo apt-get install expect
  - sudo pip install -U docker-compose
  - docker --version && docker-compose --version

install:
  - yarn install

script:
  - yarn lint
  - yarn test
  - sh bin/test.sh

notifications:
  email:
    on_success: never
    on_failure: change
