language: node_js

sudo: true

node_js: 9.4

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules

services:
  - docker

install:
  - sudo apt-get update && sudo apt-get install expect
  - yarn install

script:
  - sh tests/test.sh

notifications:
  email:
    on_success: never
    on_failure: change
