version: "3"
services:
  vue:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    volumes:
      - .:/code
    networks:
      - webnet
    ports:
      - "3000:3000"

networks:
  webnet:
